all:
  hosts:
    node1:
      ansible_host: 10.25.128.238
      ip: 10.25.128.238
      access_ip: 10.25.128.238
    node2:
      ansible_host: 10.25.128.28
      ip: 10.25.128.28
      access_ip: 10.25.128.28
    node3:
      ansible_host: 10.25.129.207
      ip: 10.25.129.207
      access_ip: 10.25.129.207
    node4:
      ansible_host: 10.25.129.181
      ip: 10.25.129.181
      access_ip: 10.25.129.181
    node5:
      ansible_host: 10.25.128.37
      ip: 10.25.128.37
      access_ip: 10.25.128.37
    node6:
      ansible_host: 10.25.128.6
      ip: 10.25.128.6
      access_ip: 10.25.128.6
    node7:
      ansible_host: 10.25.129.203
      ip: 10.25.129.203
      access_ip: 10.25.129.203
    node8:
      ansible_host: 10.25.129.243
      ip: 10.25.129.243
      access_ip: 10.25.129.243
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
        node8:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
